packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'

allowBuilds:
  better-sqlite3: true
  esbuild: true
  isolated-vm: true
  koffi: true

catalog:
  tsdown: '0.22.14'
  typescript: '7.0.2'
  '@types/node': '26.3.0'
  tsx: '4.23.12'

minimumReleaseAge: 0
